# Generated by Django 5.1.2 on 2024-11-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.IntegerField(choices=[(1, 'Choose category'), (2, 'Popular'), (3, 'Newest'), (4, 'Accessories'), (5, 'T-shirts'), (6, 'Footwear'), (7, 'Jackets'), (8, 'Others')], default=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
