# Generated by Django 5.1.2 on 2024-11-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='content',
        ),
    ]
