# Generated by Django 5.1.2 on 2024-11-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_description_product_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
