# Generated by Django 5.1.2 on 2024-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
