# Generated by Django 5.1.2 on 2024-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=1, verbose_name='Colours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=1, verbose_name='Size'),
            preserve_default=False,
        ),
    ]
