version: '3.8'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USER_PASSWORD}
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ShoppieBackend
    ports:
      - "8000:8000"
    env_file:
      - .env